config/routes.rb
Rails.application.routes.draw do
  root 'bienvenida#index'

  resources :cities_temperatures
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cities_temperature.rb
class CitiesTemperature < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bienvenida_controller.rb
class BienvenidaController < ApplicationController

	class ApiRequestFailed < StandardError; end

  def index
		require 'net/http'
		require 'json'
		
		@temperatures = Array.new
		save = false 

		#Se define la url del endpoint a consumir
		url = ENV['API_URL'] + "api/cities"
		uri = URI(url)
		begin
			#simula un 10% de posibilidades de fallar la consulta a la api
			raise BienvenidaController::ApiRequestFailed, "How unfortunate! The API Request Failed" unless rand(0.0...1.0) > 0.1

			response = Net::HTTP.get(uri)
			response = JSON.parse(response)

			#Para cumplir el requisito de solo almacenar a la base de datos pasado de 10 segundos
			#desde la ultima insercion, se define una cookie guardando la hora en que se realizo.
			if cookies[:last_update].nil?
				cookies[:last_update] = Time.now
				save = true
			end
			if cookies[:last_update] < Time.now-10
				cookies[:last_update] = Time.now
				save = true
			end

			response.each do |r|
				@temperatures.append(CitiesTemperature.new(r))
				if save
					@temperatures.last.save
				end
			end
			
		rescue BienvenidaController::ApiRequestFailed
			retry
		rescue Errno::ECONNREFUSED
			#Si cae en este error es posible que la api no este funcionando, o que la url indicada para
			#esta sea incorrecta
		end
  end
end

app/controllers/cities_temperatures_controller.rb
class CitiesTemperaturesController < ApplicationController

  def index
    @temperatures = CitiesTemperature.all.sort_by(&:temperature)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bienvenida_helper.rb
module BienvenidaHelper
end

app/helpers/cities_temperatures_helper.rb
module CitiesTemperaturesHelper
end

app/views/bienvenida/index.html.erb
<div class="mdl-cell mdl-cell--12">
	<table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp style="width:100%;">
		<thead>
			<tr>
				<th class="mdl-data-table__cell--non-numeric">Ciudad</th>
				<th>Hora<i class="material-icons md-18">schedule</i></th>
				<th>Temperatura<i class="material-icons md-18">wb_sunny</i></th>
			</tr>
		</thead>
		<tbody>
			<% @temperatures.each do |temperature| %>
				<tr>
					<td class="mdl-data-table__cell--non-numeric"><%= temperature.name%></td>
					<td><%= temperature.hour%></td>
					<td><%= temperature.temperature%></font></td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<br>
	<%= button_to "Actualizar", root_path, :method => :get, class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
</div>

app/views/cities_temperatures/index.html.erb
<div class="mdl-cell mdl-cell--12">
	<table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp style="width:100%;">
		<thead>
			<tr>
				<th class="mdl-data-table__cell--non-numeric">Ciudad</th>
				<th>Hora<i class="material-icons md-18">schedule</i></th>
				<th>Temperatura<i class="material-icons md-18">wb_sunny</i></th>
			</tr>
		</thead>
		<tbody>
		  <% if !@temperatures.blank?%>
				<% first = @temperatures.shift %>
				<% last = @temperatures.pop %>
				<tr>  
					<td class="mdl-data-table__cell--non-numeric"><%= first.name%></td>
					<td><%= first.hour%></td>
					<td><font color="#0000ff"><%= first.temperature%></font></td>
				</tr>
				<% @temperatures.each do |temperature| %>
					<tr>
						<td class="mdl-data-table__cell--non-numeric"><%= temperature.name%></td>
						<td><%= temperature.hour%></td>
						<td><%= temperature.temperature%></td>
					</tr>
				<% end %>
				<tr>  
					<td class="mdl-data-table__cell--non-numeric"><%= last.name%></td>
					<td><%= last.hour%></td>
					<td><font color="#ff0000"><%= last.temperature%></font></td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<br>
	<%= button_to "Actualizar", cities_temperatures_path, :method => :get, class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      view-source {
        position: fixed;
        display: block;
        right: 0;
        bottom: 0;
        margin-right: 40px;
        margin-bottom: 40px;
        z-index: 900;
      }
    </style>
  </head>

  <body>
    <div class="mdl-layout mdl-js-layout">
      <header class="mdl-layout__header">
        <div class="mdl-layout-icon"></div>
        <div class="mdl-layout__header-row">
          <span class="mdl-layout__title">Desafio Acid Labs</span>
          <div class="mdl-layout-spacer"></div>
          <nav class="mdl-navigation">
            <%=link_to 'Inicio', root_path, class: "mdl-navigation__link"%>
            <%=link_to 'Historial de consultas', cities_temperatures_path, class: "mdl-navigation__link"%>
          </nav>
        </div>
      </header>
    
      <main class="mdl-layout__content">
        <div class="mdl-grid">
          <div class="mdl-layout-spacer"></div>
          <%= yield %>
          <div class="mdl-layout-spacer"></div>
        </div>
      </main>
    </div>
  </body>
</html>